### Ben Porter
### This Lab is open from 11/1 at 6 am to 11/1 at 3:30 pm

We will work on a creditcard data set provided with this lab. Let's load this data. This data set is a text data. We can still use panda's read.csv function with some modifications.

In [70]:
import numpy as np
import numpy.matlib
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import preprocessing
import seaborn as sns
import scipy.stats as st
import matplotlib.colors as colors
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler  
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.datasets import make_classification  
from sklearn.neighbors import KNeighborsClassifier  
from sklearn.ensemble import RandomForestClassifier  
from sklearn.model_selection import train_test_split  
from sklearn.metrics import roc_curve 

In [38]:
credit= pd.read_csv('creditcards.txt')
credit.head(3)

A1\tA2\tA3\tA8\tA9\tA10\tA11\tA12\tA14\tA15\tR1
0        1\t30.83\t0\t1.25\t1\t0\t1\t1\t202\t0\t1
1    0\t58.67\t4.46\t3.04\t1\t0\t6\t1\t43\t560\t1
2      0\t24.5\t0.5\t1.5\t1\t1\t0\t1\t280\t824\t1

We need to separate the data where the sign \t is placed. Here \t is called a delimiter (that limits or creates the boundary for the data in each column. Let's try 

In [39]:
credit= pd.read_csv('creditcards.txt', delimiter ='\t')
credit.head(3)

A1     A2    A3    A8  A9  A10  A11  A12  A14  A15  R1
0   1  30.83  0.00  1.25   1    0    1    1  202    0   1
1   0  58.67  4.46  3.04   1    0    6    1   43  560   1
2   0  24.50  0.50  1.50   1    1    0    1  280  824   1

# Problem 1
Use sklearn to Train a logistic regression model using all the columns except 'R1'. Here 'R1' is the response or target variable and all other variables are features. Report your classification accuracy score and confusion matrix. Comment on the result. ( 15 points)

You can find out coefficents in the following way.

In [40]:

train, test = train_test_split(credit,test_size=0.25, random_state=0)
logisticRegr = LogisticRegression()
logisticRegr.fit(credit[['A1','A2','A3','A8','A9','A10','A11','A12','A14','A15']],credit[['R1']])
predictions = logisticRegr.predict(test[['A1','A2','A3','A8','A9','A10','A11','A12','A14','A15']])
conf = metrics.confusion_matrix(test[['R1']], predictions)

C:\Users\bman1\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\bman1\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [41]:
logisticRegr

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [42]:
predictions

array([1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1], dtype=int64)

In [43]:
conf

array([[74, 16],
       [ 4, 70]], dtype=int64)

In [50]:
logisticRegr.intercept_


array([-1.31144891])

In [51]:
logisticRegr.coef_

array([[-1.34850084e-01, -2.06136285e-02, -2.09015662e-02,
         1.41417460e-01,  3.34273381e+00, -8.78033782e-01,
         7.65533743e-02, -2.13710782e-02, -1.42276860e-03,
         5.11261749e-04]])

# Problem 2
After listing the values of the coefficients of all the variables, pick 5 variables whose coefficients are biggest in absolute values. Make sure to match the variable names and coefficients so that you pick the correct columns. Now retrain the logistic regression model with these 5 variables and report your accuracy details with confusion matrix. Compare this result with  the result in Problem 1. (15 points)

A9 A10 A1 A8 A11

In [52]:
train1, test1 = train_test_split(credit,test_size=0.25, random_state=0)
logisticRegr1 = LogisticRegression()
logisticRegr1.fit(credit[['A1','A8','A9','A10','A11']],credit[['R1']])
predictions1 = logisticRegr1.predict(test1[['A1','A8','A9','A10','A11']])
conf1 = metrics.confusion_matrix(test1[['R1']], predictions1)

C:\Users\bman1\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\bman1\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [54]:
logisticRegr1

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [55]:
predictions1

array([1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1], dtype=int64)

In [56]:
conf1

array([[74, 16],
       [ 3, 71]], dtype=int64)

In [57]:
logisticRegr1.intercept_

array([-2.13847877])

In [58]:
logisticRegr1.coef_

array([[-0.09655792,  0.10681625,  3.1831466 , -0.70687051,  0.12118919]])

# Problem 3
Continuing with the data you have in problem 2, divide the data to test and train using 70, 30 rule and train the logistic regression model again. Report your accuracy and confusion matrix for both the training set and the test set. Comment on the result. (10 points)

In [59]:
train2, test2 = train_test_split(credit,test_size=0.30, random_state=0)
logisticRegr2 = LogisticRegression()
logisticRegr2.fit(credit[['A1','A8','A9','A10','A11']],credit[['R1']])
predictions2 = logisticRegr2.predict(test2[['A1','A8','A9','A10','A11']])
conf2 = metrics.confusion_matrix(test2[['R1']], predictions2)

C:\Users\bman1\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\bman1\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [63]:
train2.head()

A1     A2      A3    A8  A9  A10  A11  A12  A14   A15  R1
484   1  13.75   4.000  1.75   1    0    2    0  120  1000   1
243   0  17.83  11.000  1.00   1    0   11    1    0  3000   1
402   1  20.42   1.085  1.50   0    1    0    1  108     7   0
96    1  35.25  16.500  4.00   1    1    0    1   80     0   0
354   1  26.33  13.000  0.00   0    1    0    0  140  1110   0

In [64]:
test2.head()

A1     A2      A3     A8  A9  A10  A11  A12  A14  A15  R1
535   1  24.42  12.335  1.585   1    1    0    0  120    0   1
492   1  39.17   1.710  0.125   1    0    5    0  480    0   1
14    0  45.83  10.500  5.000   1    0    7    0    0    0   1
247   1  20.00   0.000  0.500   0    1    0    1  144    0   0
85    1  34.00   4.500  1.000   1    1    0    0  240    0   0

In [65]:
logisticRegr2

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [66]:
predictions2

array([1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0],
      dtype=int64)

In [67]:
conf2

array([[90, 20],
       [ 3, 84]], dtype=int64)

In [68]:
logisticRegr2.intercept_

array([-2.13847877])

In [69]:
logisticRegr2.coef_

array([[-0.09655792,  0.10681625,  3.1831466 , -0.70687051,  0.12118919]])

All we did in this problem is slightly adjust the test aand train sizes, making the test slightly bigger and the train slightly smaller.

# Problem 4
Plot the ROC curve for the model in problem 3. Read more about ROC curve here
https://www.dataschool.io/roc-curves-and-auc-explained/ or just google and read more about ROC curve. ( 10 points)

In [71]:
def plot_roc_cur(fper, tper):  
    plt.plot(fper, tper, color='orange', label='ROC')
    plt.plot([0, 1], [0, 1], color='darkblue', linestyle='--')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver Operating Characteristic (ROC) Curve')
    plt.legend()
    plt.show()

In [72]:
data_X, cls_lab = make_classification(n_samples=1100, n_classes=2, weights=[1,1], random_state=1)  
train_X, test_X, train_y, test_y = train_test_split(data_X, cls_lab, test_size=0.3, random_state=1)

In [76]:
model = logisticRegr2()  
model.fit(trainX, trainy)

TypeError: 'LogisticRegression' object is not callable

Im not exactly sure why this did not work.